filter_secrets: false
language: node_js
node_js: stable
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
before_install:
  - npm install -g gatsby-cli
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  - npm run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=litmuschaos/www-litmuschaos-io;
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$COMMIT . && docker push $REPO;
    fi
  - if [ "$TRAVIS_BRANCH" = "staging" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=litmuschaos/www-staging-litmuschaos-io;
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$TRAVIS_BRANCH-$COMMIT . && docker push $REPO;
    fi
